
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rahimecalik
 */
public class adminEkran extends javax.swing.JFrame {

    /**
     * Creates new form adminEkran
     */
    public adminEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGeri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonIstatistikler = new javax.swing.JButton();
        jButtonLigler = new javax.swing.JButton();
        jButtonMacTakvimi = new javax.swing.JButton();
        jButtonKullanıcılarıListele = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonDosyalama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonGeri.setText("Geri");
        jButtonGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeriActionPerformed(evt);
            }
        });

        jLabel1.setText("Yapmak istediğiniz işlemi seçiniz");

        jButtonIstatistikler.setText("Istatistikler");
        jButtonIstatistikler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIstatistiklerActionPerformed(evt);
            }
        });

        jButtonLigler.setText("Ligler");
        jButtonLigler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiglerActionPerformed(evt);
            }
        });

        jButtonMacTakvimi.setText("Mac Takvimi");
        jButtonMacTakvimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMacTakvimiActionPerformed(evt);
            }
        });

        jButtonKullanıcılarıListele.setText("Kullanıcıları Listele");
        jButtonKullanıcılarıListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKullanıcılarıListeleActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Kullanıcılar");

        jButtonDosyalama.setText("tcDosya");
        jButtonDosyalama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDosyalamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMacTakvimi)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jButtonLigler))
                                .addComponent(jButtonIstatistikler))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonKullanıcılarıListele))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonDosyalama)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIstatistikler)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonLigler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMacTakvimi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKullanıcılarıListele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDosyalama)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButtonGeri))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel1)))
                        .addGap(0, 244, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGeri)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeriActionPerformed
        // Admin giriş ekranını açma
        adminGirisi giris = new adminGirisi();
        dispose();  // Mevcut pencereyi kapatma
        giris.setVisible(true);  // Yeni pencereyi açma
    }//GEN-LAST:event_jButtonGeriActionPerformed

    private void jButtonMacTakvimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMacTakvimiActionPerformed
        // Admin maç takvimi ekranını açma
        adminMacTakvimi adMacTakvimi = new adminMacTakvimi();
        dispose();
        adMacTakvimi.setVisible(true);
    }//GEN-LAST:event_jButtonMacTakvimiActionPerformed

    private void jButtonIstatistiklerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIstatistiklerActionPerformed
        // Admin istatistikler ekranını açma
        adminIstatistikler adIstatistikler = new adminIstatistikler();
        dispose();
        adIstatistikler.setVisible(true);
    }//GEN-LAST:event_jButtonIstatistiklerActionPerformed

    private void jButtonLiglerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiglerActionPerformed
        // Admin ligler ekranını açma
        adminLigler adlig = new adminLigler();
        dispose();
        adlig.setVisible(true);
    }//GEN-LAST:event_jButtonLiglerActionPerformed

    private void jButtonKullanıcılarıListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKullanıcılarıListeleActionPerformed
        // Veritabanı bağlantı bilgileri
        String url = "jdbc:mysql://127.0.0.1:3306/proje";
        String user = "root";
        String password = "Rahime4588";
        // Kullanıcı isimlerini alacak SQL sorgusu
        String query = "SELECT kullaniciAdi FROM kullanici";  // Kullanıcı isimlerini alacak sorgu
        // JList modelinin oluşturulması
        DefaultListModel<String> model = new DefaultListModel<>();
        JList<String> list = new JList<>(model);  // JList'i model ile başlat

        try (Connection conn = DriverManager.getConnection(url, user, password); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            model.clear(); // Listeyi temizle

            while (rs.next()) {
                String kullaniciAdi = rs.getString("kullaniciAdi");
                model.addElement(kullaniciAdi);  // Model'e kullanıcı adını ekle
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Veri yüklenirken hata oluştu.", "Hata", JOptionPane.ERROR_MESSAGE);
        }

        // JList'in model'ini yenile
        jList1.setModel(model);

    }//GEN-LAST:event_jButtonKullanıcılarıListeleActionPerformed

    private void jButtonDosyalamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosyalamaActionPerformed
        // Dosya işlemleri için dosya sınıfı nesnesi oluşturma
        dosya dosyaObject = new dosya();
        // Dosya yolu ve veritabanı bağlantı bilgileri
        String filePath = "kullanicilar.txt";
        String url = "jdbc:mysql://127.0.0.1:3306/proje";
        String user = "root";
        String password = "Rahime4588";
        // Kullanıcıların TC kimlik numaralarını alacak SQL sorgusu
        String query = "SELECT tc FROM kullanici";
         // TC kimlik bilgilerini dosyaya yazma ve okuma işlemleri
        dosyaObject.dosyaYazma(url, user, password, query, filePath);
        dosyaObject.dosyaOkuma(filePath);
        // İşlemin tamamlandığını kullanıcıya bildirme
        JOptionPane.showMessageDialog(this, "Kullanıcıların Tc kimlik bilgileri dosyaya yazdırıldı. ", "duyuru", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButtonDosyalamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDosyalama;
    private javax.swing.JButton jButtonGeri;
    private javax.swing.JButton jButtonIstatistikler;
    private javax.swing.JButton jButtonKullanıcılarıListele;
    private javax.swing.JButton jButtonLigler;
    private javax.swing.JButton jButtonMacTakvimi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
