
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rahimecalik
 */
public class adminIstatistikler extends javax.swing.JFrame {

    /**
     * Creates new form adminIstatistikler
     */
    public adminIstatistikler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jButtonISGörüntüle = new javax.swing.JButton();
        jRadioButtonGeri = new javax.swing.JRadioButton();
        jRadioButtonExit = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdminIstatistik = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButtonIstatistikGörüntüle = new javax.swing.JButton();
        jButtonIstatistikEkle = new javax.swing.JButton();
        jButtonIstatistikSil = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonISGörüntüle.setText("Istatistik Görüntüle");
        jButtonISGörüntüle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonISGörüntüleActionPerformed(evt);
            }
        });

        jRadioButtonGeri.setText("< Geri");
        jRadioButtonGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGeriActionPerformed(evt);
            }
        });

        jRadioButtonExit.setText("Exit >");

        jTableAdminIstatistik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAdminIstatistik);

        jLabel1.setText("Sıra");

        jLabel2.setText("Kulüp");

        jLabel3.setText("İsim");

        jLabel4.setText("Soyisim");

        jLabel5.setText("Pozisyon");

        jButtonIstatistikGörüntüle.setText("Görüntüle");
        jButtonIstatistikGörüntüle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIstatistikGörüntüleActionPerformed(evt);
            }
        });

        jButtonIstatistikEkle.setText("Ekle");
        jButtonIstatistikEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIstatistikEkleActionPerformed(evt);
            }
        });

        jButtonIstatistikSil.setText("Sil");
        jButtonIstatistikSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIstatistikSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButtonGeri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(12, 180, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jButtonIstatistikGörüntüle)
                                .addGap(80, 80, 80)
                                .addComponent(jButtonIstatistikEkle)
                                .addGap(86, 86, 86)
                                .addComponent(jButtonIstatistikSil))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jButtonISGörüntüle, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonISGörüntüle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIstatistikGörüntüle)
                    .addComponent(jButtonIstatistikEkle)
                    .addComponent(jButtonIstatistikSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonGeri)
                    .addComponent(jRadioButtonExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGeriActionPerformed
adminEkran ekran = new adminEkran();
        dispose();
        ekran.setVisible(true);       
    }//GEN-LAST:event_jRadioButtonGeriActionPerformed
public DefaultTableModel veriGetir() throws SQLException {
    Connection c = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/proje", "root", "Rahime4588");
    Statement s = c.createStatement();
    ResultSet resultSet = s.executeQuery("SELECT * FROM proje.istatistik");
            
    ResultSetMetaData metaData = resultSet.getMetaData();
    int sütunSayısı = metaData.getColumnCount();
            
    DefaultTableModel model = new DefaultTableModel();
    for (int i = 1; i <= sütunSayısı; i++) {
        model.addColumn(metaData.getColumnName(i));
    }
    while (resultSet.next()) {
        Object[] row = new Object[sütunSayısı];
        for (int i = 1; i <= sütunSayısı; i++) {
            row[i - 1] = resultSet.getObject(i);
        }
        model.addRow(row);
    }
                    
    resultSet.close();
    s.close();
    c.close();
    
    return model;
}
    private void jButtonISGörüntüleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonISGörüntüleActionPerformed
         
        try {
             // veriGetir metodunu çağırarak veritabanından verileri al
    DefaultTableModel model = veriGetir();
    // Alınan verileri jTableAdminIstatistik'e ayarla
    jTableAdminIstatistik.setModel(model);
} catch (SQLException ex) {
    ex.printStackTrace();
} 
    }//GEN-LAST:event_jButtonISGörüntüleActionPerformed

    private void jButtonIstatistikGörüntüleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIstatistikGörüntüleActionPerformed

        try {
             // veriGetir metodunu çağırarak veritabanından verileri al
    DefaultTableModel model = veriGetir();
    // Alınan verileri jTableAdminIstatistik'e ayarla
    jTableAdminIstatistik.setModel(model);
} catch (SQLException ex) {
    ex.printStackTrace();
}       
    }//GEN-LAST:event_jButtonIstatistikGörüntüleActionPerformed

    private void jButtonIstatistikEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIstatistikEkleActionPerformed
       DefaultTableModel model = new DefaultTableModel();
        try {
    Connection c = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/proje", "root", "Rahime4588");
String insertQuery = "INSERT INTO istatistik (sira, kulüp, isim, soyisim, pozisyon) VALUES (?, ?, ?, ?, ?)";
PreparedStatement st = c.prepareStatement(insertQuery);

 // TextField'lardan kullanıcı girdilerini alma
String sira = jTextField1.getText();
String kulüp = jTextField2.getText();
String isim = jTextField3.getText();
String soyisim = jTextField4.getText();
String pozisyon = jTextField5.getText();

// TextField'ların boş olup olmadığını kontrol et
    if (sira.isEmpty() || kulüp.isEmpty() || isim.isEmpty() || soyisim.isEmpty() || pozisyon.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Lütfen tüm alanları doldurun.", "Uyarı", JOptionPane.WARNING_MESSAGE);
        return; // İşlemi sonlandır
    }


// SQL sorgusu için parametreleri ayarla
st.setString(1, sira);
    st.setString(2, kulüp);
  st.setString(3, isim);
   st.setString(4, soyisim);
    st.setString(5, pozisyon);
    
    // SQL sorgusunu çalıştır ve veri ekle
    st.executeUpdate();
    JOptionPane.showMessageDialog(null, "Seçilen kullanıcı başarıyla eklendi.");
    st.close();
    c.close();
    
  jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    
        } catch (SQLException ex) {
            // SQL hatası durumunda hata mesajını yazdır
    ex.printStackTrace(); 
    
}
    }//GEN-LAST:event_jButtonIstatistikEkleActionPerformed

    private void jButtonIstatistikSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIstatistikSilActionPerformed
try {
    // Kullanıcının seçtiği satırın indeksini al
            int selectedRow = jTableAdminIstatistik.getSelectedRow();
            // Eğer kullanıcı hiçbir satır seçmemişse, uyarı mesajı göster
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Lütfen silinecek satırı seçin.");
            } else {
                // Veritabanına bağlantı kur
                Connection c = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/proje","root","Rahime4588");
                Statement s = c.createStatement();
// Seçilen satırın ikinci sütunundaki veriyi al
                Object kulüpObject = jTableAdminIstatistik.getModel().getValueAt(selectedRow, 1);
                String kulüpToDelete;
                // Eğer veri String türündeyse, bu veriyi silinecek kulüp ismi olarak kullan
                if (kulüpObject instanceof String) {
                    kulüpToDelete = (String) kulüpObject;
                } else {
                    // Eğer veri türü uygun değilse, hata fırlat
                    throw new IllegalArgumentException("Değişken tipi hatası oluştu.");
                }

                // Veritabanından ilgili kaydı sil
                String sql = "DELETE FROM proje.istatistik WHERE kulüp = '" + kulüpToDelete + "'";
                s.executeUpdate(sql);

                // JTable'den satırı kaldır
                ((DefaultTableModel) jTableAdminIstatistik.getModel()).removeRow(selectedRow);

                s.close();
                c.close();
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Veritabanı işlemi sırasında bir hata oluştu.");
        } catch (IllegalArgumentException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Sütun hatalı türde veri içeriyor.");
        }       
    }//GEN-LAST:event_jButtonIstatistikSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminIstatistikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminIstatistikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminIstatistikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminIstatistikler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminIstatistikler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonISGörüntüle;
    private javax.swing.JButton jButtonIstatistikEkle;
    private javax.swing.JButton jButtonIstatistikGörüntüle;
    private javax.swing.JButton jButtonIstatistikSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JRadioButton jRadioButtonExit;
    private javax.swing.JRadioButton jRadioButtonGeri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdminIstatistik;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
