
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rahimecalik
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1üyeGirisi = new javax.swing.JButton();
        jButton2adminGirisi = new javax.swing.JButton();
        jButton3kayitOl = new javax.swing.JButton();
        jButton1duyurular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Voleybol Müsabakası Takip Sistemi");

        jButton1üyeGirisi.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1üyeGirisi.setText("Üye Girisi");
        jButton1üyeGirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1üyeGirisiActionPerformed(evt);
            }
        });

        jButton2adminGirisi.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2adminGirisi.setText("Admin Girisi");
        jButton2adminGirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2adminGirisiActionPerformed(evt);
            }
        });

        jButton3kayitOl.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton3kayitOl.setText("Kayıt Ol");
        jButton3kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3kayitOlActionPerformed(evt);
            }
        });

        jButton1duyurular.setFont(new java.awt.Font("Krungthep", 1, 14)); // NOI18N
        jButton1duyurular.setText("Duyurular&Haberler");
        jButton1duyurular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1duyurularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1üyeGirisi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton2adminGirisi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton3kayitOl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton1duyurular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jButton1üyeGirisi)
                .addGap(18, 18, 18)
                .addComponent(jButton2adminGirisi)
                .addGap(18, 18, 18)
                .addComponent(jButton3kayitOl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1duyurular)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Bu sayfadaki ilk 3 butonun amacı bulunduğu sayfayı kapatıp görünür yaptığımız sayfaya geçmektir. 

    private void jButton1üyeGirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1üyeGirisiActionPerformed
        uyeGirisi uye=new uyeGirisi();
        dispose();
        uye.setVisible(true);
    }//GEN-LAST:event_jButton1üyeGirisiActionPerformed

    private void jButton3kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3kayitOlActionPerformed
        uyeKayit kayit=new uyeKayit();
        dispose();
        kayit.setVisible(true);
    }//GEN-LAST:event_jButton3kayitOlActionPerformed

    private void jButton2adminGirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2adminGirisiActionPerformed
       adminGirisi admin = new adminGirisi();
       dispose();
       admin.setVisible(true);
    }//GEN-LAST:event_jButton2adminGirisiActionPerformed

// Bu buton voleybol müsabakaları ile ilgili bilgilendiri bir duyuru methodudur.     
    private void jButton1duyurularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1duyurularActionPerformed
       JOptionPane.showMessageDialog(this, "Filenin Sultanları, Japonya'ya 3-2 mağlup oldu \n2024 FIVB Voleybol Milletler Ligi heyecanı Antalya'da başladı ", "duyuru", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1duyurularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1duyurular;
    private javax.swing.JButton jButton1üyeGirisi;
    private javax.swing.JButton jButton2adminGirisi;
    private javax.swing.JButton jButton3kayitOl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
