
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rahimecalik
 */
public class lig2 extends javax.swing.JFrame {

    /**
     * Creates new form kadinlar2Lig
     */
    public lig2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1geri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonLig2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1geri.setText("Geri");
        jButton1geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1geriActionPerformed(evt);
            }
        });

        jLabel1.setText("2.Lig");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonLig2.setText("Ligleri Görüntüle");
        jButtonLig2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLig2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1geri))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButtonLig2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLig2)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton1geri)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1geriActionPerformed
        uyeEkran ekran = new uyeEkran();
        dispose();
        ekran.setVisible(true);
    }//GEN-LAST:event_jButton1geriActionPerformed

    private void jButtonLig2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLig2ActionPerformed
        try {
            // Veritabanına bağlantı kurulması
            Connection c = DriverManager.getConnection("jdbc:mysql://127.0.01:3306/proje", "root", "Rahime4588");
            Statement s = c.createStatement();
            // "lig2" tablosundaki tüm verileri sorgulama
            ResultSet resultSet = s.executeQuery("SELECT * FROM proje.lig2");
            // Meta veri bilgilerini almak için ResultSetMetaData nesnesi oluşturma
            ResultSetMetaData metaData = resultSet.getMetaData();
            // Sonuç kümesindeki sütun sayısını elde etme
            int sütunSayısı = metaData.getColumnCount();
            // DefaultTableModel oluşturma
            DefaultTableModel model = new DefaultTableModel();
            // Sütun isimlerini tablo modeline ekleme
            for (int i = 1; i <= sütunSayısı; i++) {
                model.addColumn(metaData.getColumnName(i));

            }
            // Veritabanından alınan verileri tablo modeline ekleme
            while (resultSet.next()) {
                // Her satır için bir dizi oluşturma
                Object[] row = new Object[sütunSayısı];
                // Sütunlardaki verileri diziye ekleme
                for (int i = 1; i <= sütunSayısı; i++) {
                    row[i - 1] = resultSet.getObject(i);
                }
                // Diziyi tablo modeline bir satır olarak ekleme
                model.addRow(row);
            }
            // JTable'a oluşturulan tablo modelini ekleme         
            jTable1.setModel(model);
            // Kaynakları kapatma
            resultSet.close();
            s.close();
            c.close();
        } catch (SQLException ex) {
            // SQL hatası durumunda hata mesajını yazdırma
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonLig2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lig2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lig2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lig2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lig2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lig2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1geri;
    private javax.swing.JButton jButtonLig2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
