/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rahimecalik
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class uyeGirisi extends javax.swing.JFrame {

    /**
     * Creates new form üyeGirisi
     */
    public uyeGirisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1ePosta = new javax.swing.JLabel();
        jTextField1ePosta = new javax.swing.JTextField();
        jLabel2sifre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1geri = new javax.swing.JButton();
        jButton1giris = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel1ePosta.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1ePosta.setText("E-posta");

        jTextField1ePosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ePostaActionPerformed(evt);
            }
        });

        jLabel2sifre.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2sifre.setText("Sifre");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Üye Girisi");

        jButton1geri.setText("Geri");
        jButton1geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1geriActionPerformed(evt);
            }
        });

        jButton1giris.setText("Giris");
        jButton1giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1girisActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton1geri)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1giris)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addComponent(jLabel1ePosta))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addComponent(jTextField1ePosta, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1ePosta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1ePosta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2sifre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1geri)
                    .addComponent(jButton1giris))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ePostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ePostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ePostaActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded

    }//GEN-LAST:event_formComponentAdded
//Geri butonları ile bir önceki sayfaya dönebiliriz.
    private void jButton1geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1geriActionPerformed
        GirisEkrani giris = new GirisEkrani();
        dispose();
        giris.setVisible(true);

    }//GEN-LAST:event_jButton1geriActionPerformed

    private void jButton1girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1girisActionPerformed
        //Veri tabanına bağlantı
        Connection c;
        ResultSet rs;
        String ep = "";

        //jPasswordField1.getPassword ile şifre alanındaki veriyi alıp String değere dönüştürme
        char[] sifre = jPasswordField1.getPassword();
        String password = String.valueOf(sifre);
        String sifreText = "";

        try {
            // Veritabanına bağlantı kurulması
            c = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/proje", "root", "Rahime4588");
            // Kullanıcının girdiği e-posta adresinin alınması
            String email = jTextField1ePosta.getText();
            // E-posta veya şifrenin boş olup olmadığının kontrol edilmesi
            if (email.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "E-posta veya şifre boş bırakılamaz.", "Uyarı", JOptionPane.WARNING_MESSAGE);
                throw new Exception("E-posta veya şifre boş bırakılamaz.");
            // E-posta adresinin geçerliliğinin kontrol edilmesi
            } else if (!email.matches("^[a-zA-Z0-9._]+@gmail\\.[a-z]+$")) {
                JOptionPane.showMessageDialog(this, "Geçersiz e-posta adresi.", "Uyarı", JOptionPane.WARNING_MESSAGE);
                throw new Exception("Geçersiz e-posta adresi.");
            }
            // Veritabanındaki SQL sorgusunda seçili sablonun belirtilen parametrelerine ulaşıyor. 
            String sorgu = "SELECT * FROM proje.kullanici WHERE eposta = ? AND sifre = ?";
            PreparedStatement ps = c.prepareStatement(sorgu);
            ps.setString(1, email);
            ps.setString(2, password);
            // Sorgunun çalıştırılması ve sonuç kümesinin alınması
            rs = ps.executeQuery();
            // Sonuç kümesinde kayıt olup olmadığının kontrol edilmesi
            if (rs.next()) {
                // Giriş başarılıysa yeni bir ekran açılması
                new uyeEkran().setVisible(true);

                JOptionPane.showMessageDialog(this, "Giriş başarılı", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
                dispose(); // Mevcut pencerenin kapatılması
            } else {
                JOptionPane.showMessageDialog(null, "Kullanıcı kayıtlı değil veya şifre yanlış, lütfen üye olun veya bilgilerinizi kontrol edin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
            } // Giriş başarısızsa uyarı mesajı gösterilmesi

        } catch (SQLException ex) {
            ex.printStackTrace(); // Veritabanı hatası oluşursa hata mesajı gösterilmesi
            JOptionPane.showMessageDialog(this, "Veritabanı hatası oluştu.", "Hata", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) { // Diğer hatalar için uyarı mesajı gösterilmesi
            JOptionPane.showMessageDialog(this, e.getMessage(), "Uyarı", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1girisActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uyeGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uyeGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uyeGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uyeGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uyeGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1geri;
    private javax.swing.JButton jButton1giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1ePosta;
    private javax.swing.JLabel jLabel2sifre;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1ePosta;
    // End of variables declaration//GEN-END:variables
}
