
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rahimecalik
 */
public class uyeMacTakvimi extends javax.swing.JFrame {

    /**
     * Creates new form uyeMacTakvimi
     */
    public uyeMacTakvimi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMacTakvimi = new javax.swing.JTable();
        jButtonMacTakvimi = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuGeri = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("null");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("null");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMacTakvimi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMacTakvimi);

        jButtonMacTakvimi.setText("MacTakvimi");
        jButtonMacTakvimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMacTakvimiActionPerformed(evt);
            }
        });

        jMenuExit.setText("Exit");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Exit");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenuExit.add(jCheckBoxMenuItem1);

        jMenuBar2.add(jMenuExit);

        jMenuGeri.setText("Geri");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Geri");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenuGeri.add(jCheckBoxMenuItem2);

        jMenuBar2.add(jMenuGeri);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMacTakvimi)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jButtonMacTakvimi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMacTakvimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMacTakvimiActionPerformed
        // Maç Takvimi butonuna tıklandığında çalışacak kod
        try {
            // Veritabanına bağlantı kurulması
            Connection c =DriverManager.getConnection("jdbc:mysql://127.0.01:3306/proje","root","Rahime4588");
            Statement s = c.createStatement();
            // "takvim" tablosundaki tüm verileri sorgulama
            ResultSet resultSet = s.executeQuery("SELECT * FROM proje.takvim");
            // Meta veri bilgilerini almak için ResultSetMetaData nesnesi oluşturma
            ResultSetMetaData metaData = resultSet.getMetaData();
            // Sonuç kümesindeki sütun sayısını elde etme
            int sütunSayısı= metaData.getColumnCount();
            // DefaultTableModel oluşturma
            DefaultTableModel model = new DefaultTableModel();
             for (int i = 1; i <= sütunSayısı; i++) {
                 model.addColumn(metaData.getColumnName(i));
                 
             }
             // Veritabanından alınan verileri tablo modeline ekleme
            while (resultSet.next()){
                // Her satır için bir dizi oluşturma
                Object[]row = new Object[sütunSayısı];
                // Sütunlardaki verileri diziye ekleme
                for (int i = 1; i <= sütunSayısı; i++) {
                    row [i-1]=resultSet.getObject(i);
                }
                 // Diziyi tablo modeline bir satır olarak ekleme
                model.addRow(row);
            }
          // JTable'a oluşturulan tablo modelini ekleme          
          jTableMacTakvimi.setModel(model);
           // Kaynakları kapatma
          resultSet.close();
          s.close();
          c.close();
        }
        catch (SQLException ex) {
            // SQL hatası durumunda hata mesajını yazdırma
           ex.printStackTrace();
        }
    
    }//GEN-LAST:event_jButtonMacTakvimiActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
       // CheckBoxMenuItem2 tıklandığında çalışacak kod
        uyeEkran ekran =new uyeEkran(); // yeni üye ekranı oluşturma
       ekran.setVisible(true); // yeni üye ekranını görünür yapma
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
    // CheckBoxMenuItem1 tıklandığında pencereyi kapatma
        dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uyeMacTakvimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uyeMacTakvimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uyeMacTakvimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uyeMacTakvimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uyeMacTakvimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMacTakvimi;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuGeri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMacTakvimi;
    // End of variables declaration//GEN-END:variables
}
